package com.jordanbunke.painterly.resources;

import com.jordanbunke.painterly.util.EnumUtils;

public enum ResourceCode {
    RC_NA, // special resource code indicating N/A
    RC_UNKNOWABLE,
    RC_UNKNOWN,

    // Icons
    RC_CHECKED_FALSE,
    RC_CHECKED_TRUE,
    RC_FEEDBACK_INVALID,
    RC_FEEDBACK_VALID,
    RC_DECREMENT,
    RC_INCREMENT,

    // Misc. images
    RC_CONTROL_POINT,
    RC_HIGHLIGHT,
    RC_ICON,

    // UI text
    RC_ABOUT, // also: tooltip

    // Are you sure
    RC_AYS_CLOSE_PROJECT_MESSAGE,
    RC_AYS_CLOSE_PROJECT_TITLE,
    RC_AYS_DELETE_ACTIVE_BOUNDS_MESSAGE,
    RC_AYS_DELETE_ACTIVE_BOUNDS_TITLE,
    RC_AYS_QUIT_MESSAGE,
    RC_AYS_QUIT_TITLE,

    // Context bar
    RC_CB_CURRENT_TOOL,
    RC_CB_DIVS_X,
    RC_CB_DIVS_Y,
    RC_CB_FOCUS_BOX_MODE,
    RC_CB_INTERVAL_TARGET,
    RC_CB_INTERVAL_PROGRESS,
    RC_CB_SIMILARITY,
    RC_CB_STROKES_ATTEMPTED,
    RC_CB_STROKES_COMPLETED,

    // Log channel ID
    RC_CHANNEL_ID_FOCUS_BOX_REASONING,
    RC_CHANNEL_ID_INTERVAL_STATS,
    RC_CHANNEL_ID_SAVE_EXPORT,

    // Log channel actions
    RC_CHANNEL_TOGGLE_ALL,
    RC_CHANNEL_TOGGLE_FPS,
    RC_CHANNEL_TOGGLE_RECENT_STROKES,
    RC_CHANNEL_UPDATE_STATUS,

    RC_CLEAR_FOCUS_BOXES,
    RC_CLOSE_PROJECT,
    RC_COPYRIGHT,
    RC_DELETE_ACTIVE_BOUNDS,

    // DIALOG
    // Dialog feedback
    RC_DIALOG_FB_CANNOT_BE_EMPTY,
    RC_DIALOG_FB_CANNOT_BE_ONLY_WHITESPACE,
    RC_DIALOG_FB_CANNOT_READ_DOUBLE,
    RC_DIALOG_FB_CANNOT_READ_INT,
    RC_DIALOG_FB_CANNOT_VALIDATE_SCALE_FACTOR_WITHOUT_IMAGE,
    RC_DIALOG_FB_CONTAINS_INVALID_CHARACTER,
    RC_DIALOG_FB_MUST_BE_GR_EQ_1,
    RC_DIALOG_FB_NPD_VALIDATED_FOLDER,
    RC_DIALOG_FB_NPD_VALIDATED_SRC_IMAGE,
    RC_DIALOG_FB_NPD_VALIDATED_SCALE_FACTOR,
    RC_DIALOG_FB_PV_VALIDATED_FOLDER,
    RC_DIALOG_FB_VARIABLE_CANNOT_BE_NULL,
    // Dialog text
    RC_DIALOG_TX_SAVE_FOLDER,
    RC_DIALOG_TX_PROJECT_NAME,
    RC_DIALOG_TX_SOURCE_IMAGE,
    RC_DIALOG_TX_SCALE_FACTOR,
    RC_DIALOG_TX_AUTOSAVE,
    RC_DIALOG_TX_AUTOSAVE_FREQUENCY,
    RC_DIALOG_TX_AUTOSAVE_FREQUENCY_PREFIX,
    RC_DIALOG_TX_AUTOSAVE_FREQUENCY_SUFFIX,
    // Dialog UI element text
    RC_DIALOG_UI_CANCEL,
    RC_DIALOG_UI_CHOOSE_FOLDER,
    RC_DIALOG_UI_CLOSE,
    RC_DIALOG_UI_DEFAULT_OK,
    RC_DIALOG_UI_UPLOAD,

    RC_DISPLAY_FOCUS,
    RC_DISPLAY_GLOBAL,
    RC_DUPLICATE_PROJECT,
    RC_EDIT_PROJECT_SETTINGS,

    // Error codes
    RC_ERR_COULD_NOT_PARSE_SPEC_AS_JSON,
    RC_ERR_COULD_NOT_READ_FOLDER_FROM_SPEC,
    RC_ERR_COULD_NOT_READ_NAME_FROM_SPEC,
    RC_ERR_COULD_NOT_READ_PAINTING,
    RC_ERR_COULD_NOT_READ_SOURCE,
    RC_ERR_NO_SPEC_PATH,

    // Error scenarios
    RC_ERR_SC_OPEN_PROJECT,

    RC_EXPORT,

    // Focus box modes
    RC_FB_BACKWARDS,
    RC_FB_FREE,
    RC_FB_FORWARDS,
    RC_FB_PRIORITIZE_WORST,
    RC_FB_RANDOM,
    RC_FB_WORST,

    RC_FIT_TO_FOCUS_AREA,
    RC_FOCUS_AREA_AS_FOCUS_BOX,
    RC_FOCUS_AREA_AS_FOCUS_BOX_MAXIMAL,
    RC_FOCUS_BOX_AS_FOCUS_AREA,

    // Loading messages
    RC_LOAD_INIT_PROJECT,
    RC_LOAD_LOAD_PROJECT,
    RC_LOAD_UPDATE_STATS,

    // Log messages
    RC_LOG_AUTOSAVED,
    RC_LOG_EXPORTED,
    RC_LOG_INTERVAL_RATIO,
    RC_LOG_PRIORITIZE_WORST,
    RC_LOG_SAVED,
    RC_LOG_WORST,

    // Navigation
    RC_NAV_EDIT,
    RC_NAV_FOCUS_AREA,
    RC_NAV_MAIN_MENU,
    RC_NAV_PROGRAM,
    RC_NAV_PROJECT,
    RC_NAV_QUIT_PROGRAM,
    RC_NAV_VIEW,

    RC_NEW_PROJECT, // also: tooltip,
    RC_NO_PROJECTS_OPEN,
    RC_OFD_ACCEPTED_RASTER_TYPES,
    RC_OPEN_PROJECT, // also: tooltip,
    RC_PROGRAM_SETTINGS, // also: tooltip,
    RC_PROJECT_ZIP_DESCRIPTION,
    RC_QUIT,
    RC_RESET_FOCUS_AREA,
    RC_RESET_POS,

    RC_SAVE,
    RC_SAVE_AS,
    RC_START,
    RC_TICK_MODE_ATTEMPTED,
    RC_TICK_MODE_COMPLETED,
    RC_TOGGLE_FULLSCREEN,
    RC_TOGGLE_SIM,
    RC_TOGGLE_TICK_MODE,
    RC_TOGGLE_SOURCE,

    // Tools
    RC_TOOL_DRAW_FOCUS_AREA,
    RC_TOOL_FOCUS_BOX_SELECT,
    RC_TOOL_HAND,
    RC_TOOL_MOVE_FOCUS_AREA,
    RC_TOOL_ZOOM,

    // Values
    RC_MEASURING_ACCEPTED,
    RC_MEASURING_ATTEMPTED,
    RC_EXIT_FULLSCREEN,
    RC_FULLSCREEN,
    RC_OFF,
    RC_ON,
    RC_DISABLED,
    RC_ENABLED,
    RC_SCOPE_FOCUS_AREA,
    RC_SCOPE_GLOBAL,
    RC_SIM_PAUSE,
    RC_SIM_RESUME
    ;

    private final static String prefix = "RC_";

    public String id() {
        return EnumUtils.formattedNameNoPrefix(this, prefix);
    }

    public ResourceValue asValue() {
        return ResourceValue.ofRC(this);
    }

    @Override
    public String toString() {
        return id();
    }
}
